### PR TITLE
Added Manifest.in file to include requirements.txt

### PR DESCRIPTION
**Pull request by guzmanvig**
solves #6

### CODE REVIEW

**Comment by guzmanvig** [comment]
Fix made using: https://docs.python.org/2/distutils/sourcedist.html#the-manifest-in-template

**Review by jjti — APPROVED** [review]
LGTM and thank you!

**Comment by jjti** [comment]
I think this just needs a patch @guzmanvig, not a minor bump

**Comment by guzmanvig** [comment]
> I think this just needs a patch @guzmanvig, not a minor bump

Sounds good! I'll do that.

**Pull request merged**
